/* LogicLab v3 — Navigation, theme, search and common utilities */
(function(){'use strict';
(function loadThemeCSS(){if(document.getElementById('logiclab-theme-css')||document.querySelector('link[data-logiclab-theme]'))return;const link=document.createElement('link');link.id='logiclab-theme-css';link.rel='stylesheet';link.href='css/theme.css?v=3.1.0';document.head.appendChild(link)})();
const ThemeManager={init(){const saved=localStorage.getItem('logiclab-theme')||'dark';this.set(saved,false);this.bind()},set(theme,save=true){theme=theme==='light'?'light':'dark';document.documentElement.setAttribute('data-theme',theme);const btn=document.getElementById('themeToggle');const icon=btn?.querySelector('.theme-icon');const label=btn?.querySelector('.theme-label');if(icon)icon.textContent=theme==='dark'?'☀️':'🌙';if(label)label.textContent=theme==='dark'?'Light':'Dark';const mobile=document.getElementById('themeToggleMobile');const mobileIcon=mobile?.querySelector('.theme-icon');if(mobileIcon)mobileIcon.textContent=theme==='dark'?'☀️':'🌙';if(save)localStorage.setItem('logiclab-theme',theme)},toggle(){const current=document.documentElement.getAttribute('data-theme');this.set(current==='dark'?'light':'dark')},bind(){document.getElementById('themeToggle')?.addEventListener('click',()=>this.toggle());document.getElementById('themeToggleMobile')?.addEventListener('click',()=>this.toggle())}};
const SidebarManager={init(){this.sidebar=document.getElementById('sidebar');this.overlay=document.getElementById('sidebarOverlay');this.menuBtn=document.getElementById('menuToggle');this.closeBtn=document.getElementById('sidebarClose');this.menuBtn?.addEventListener('click',()=>this.open());this.closeBtn?.addEventListener('click',()=>this.close());this.overlay?.addEventListener('click',()=>this.close());document.addEventListener('keydown',e=>{if(e.key==='Escape')this.close()});this.sidebar?.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>{if(innerWidth<=768)this.close()}))},open(){this.sidebar?.classList.add('open');this.overlay?.classList.add('visible');document.body.classList.add('sidebar-open')},close(){this.sidebar?.classList.remove('open');this.overlay?.classList.remove('visible');document.body.classList.remove('sidebar-open')}};
const ScrollTopManager={init(){this.btn=document.getElementById('scrollTopBtn');if(!this.btn)return;this.btn.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));addEventListener('scroll',()=>this.toggle(),{passive:true});this.toggle()},toggle(){this.btn?.classList.toggle('visible',scrollY>400)}};
const SearchManager={index:null,init(){const input=document.getElementById('globalSearch');if(!input)return;input.addEventListener('input',e=>this.handle(e.target.value));this.loadIndex()},async loadIndex(){try{const res=await fetch('search-index.json',{cache:'no-store'});if(res.ok)this.index=await res.json();else this.index=this.buildInlineIndex()}catch(e){this.index=this.buildInlineIndex()}},buildInlineIndex(){return[{title:'Number Systems',url:'converter.html',desc:'Binary, Decimal, Octal, Hexadecimal conversions'},{title:'Logic Gates',url:'gates.html',desc:'AND, OR, NOT, NAND, NOR, XOR, XNOR'},{title:'Truth Tables',url:'truth-tables.html',desc:'Generate and view truth tables'},{title:'Binary Arithmetic',url:'arithmetic.html',desc:'Addition, Subtraction, Multiplication, Division'},{title:'Complements',url:'complements.html',desc:'1s and 2s complement calculations'},{title:'Half Adder',url:'half-adder.html',desc:'Sum and Carry circuit'},{title:'Full Adder',url:'full-adder.html',desc:'3-input adder circuit'},{title:'Flip-Flops',url:'flipflops.html',desc:'SR, JK, D, T flip-flops'},{title:'Multiplexer',url:'multiplexer.html',desc:'MUX configurations'},{title:'Demultiplexer',url:'demultiplexer.html',desc:'DEMUX configurations'},{title:'Encoder',url:'encoder.html',desc:'Priority and standard encoders'},{title:'Decoder',url:'decoder.html',desc:'2-to-4 and 3-to-8 decoders'},{title:'Formula Sheet',url:'formulas.html',desc:'Quick revision formulas'},{title:'Quiz',url:'quiz.html',desc:'Test your knowledge'},{title:'Notes',url:'notes.html',desc:'Concise study notes'}]},handle(query){const q=query.trim().toLowerCase(),el=document.getElementById('searchResults');if(!el)return;if(!q){el.innerHTML='';el.style.display='none';return}const items=(this.index||this.buildInlineIndex()).filter(it=>it.title.toLowerCase().includes(q)||it.desc.toLowerCase().includes(q));el.innerHTML=items.length?items.slice(0,8).map(it=>`<a href="${it.url}" class="search-result-item"><div class="search-result-title">${this.highlight(it.title,q)}</div><div class="search-result-desc">${this.highlight(it.desc,q)}</div></a>`).join(''):'<div class="search-empty">No results found</div>';el.style.display='block'},highlight(text,q){const escaped=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return text.replace(new RegExp(`(${escaped})`,'gi'),'<mark>$1</mark>')}};
const NavHighlight={init(){const path=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-nav]').forEach(el=>{if(el.dataset.nav===path||(path===''&&el.dataset.nav==='index.html'))el.classList.add('active')})}};
const BinaryBg={init(){const c=document.getElementById('binaryBg');if(!c)return;let html='';for(let i=0;i<7;i++){let line='';for(let j=0;j<55;j++)line+='01'[Math.floor(Math.random()*2)];html+=`<div class="binary-bg" style="top:${12+i*12}%;left:-2%;position:absolute;white-space:nowrap;">${line}</div>`}c.innerHTML=html}};
window.copyToClipboard=function(text,btn){const done=()=>{if(!btn)return;const original=btn.innerHTML;btn.innerHTML='✓ Copied!';btn.style.color='var(--success)';setTimeout(()=>{btn.innerHTML=original;btn.style.color=''},1500)};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(done).catch(fallback);else fallback();function fallback(){const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');done()}catch(e){}ta.remove()}};
window.showToast=function(message,type='success'){let toast=document.getElementById('toast');if(!toast){toast=document.createElement('div');toast.id='toast';document.body.appendChild(toast)}toast.className=`toast toast-${type} show`;toast.textContent=message;clearTimeout(window._toastTimer);window._toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)};
document.addEventListener('DOMContentLoaded',()=>{ThemeManager.init();SidebarManager.init();ScrollTopManager.init();SearchManager.init();NavHighlight.init();BinaryBg.init()});
})();
